image: debian:testing

before_script:
  - apt-get update -y
  - apt-get install -y build-essential libadwaita-1-dev meson rustup
  - rustup default stable
  - rustup toolchain install nightly
  - rustup component add clippy rustfmt

stages:
  - lint
  - build

lint:
  stage: lint
  script:
    - meson setup build -Ddemo=true
    - CARGO_HOME=build/cargo cargo +nightly fmt --all --check
    - CARGO_HOME=build/cargo cargo clippy --target-dir build/target --workspace --no-deps -- -D warnings

build:
  stage: build
  script:
    - meson setup build -Ddemo=true -Dbuildtype=release
    - meson compile -C build
  artifacts:
    paths:
      - build/server/phosh-syncbus
      - build/demo/phosh-syncbus-demo
