[workspace]
default-members = ["phosh-session-services", "phosh-os-updater", "phosh-syncbus"]
members = ["phosh-session-services", "demo", "phosh-os-updater", "phosh-syncbus"]
resolver = "3"

[workspace.package]
edition = "2024"
version = "0.2.1"

[workspace.lints.clippy]
all = "deny"
pedantic = "deny"
